{
 "title": "Management",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "users",
    "label": "User",
    "query": "SELECT DISTINCT user_name\nFROM events\nWHERE $__timeFilter(timestamp)\n  AND source = 'client'"
   },
   {
    "name": "projects",
    "label": "Project",
    "query": "SELECT DISTINCT project_id\nFROM events\nWHERE  $__timeFilter(timestamp)\n  AND project_id IS NOT NULL\n  AND source = 'client'"
   },
   {
    "name": "tasks",
    "label": "Task",
    "query": "SELECT DISTINCT task_id\nFROM events\nWHERE $__timeFilter(timestamp) \n  AND task_id IS NOT NULL\n  AND source = 'client'\n  AND (-1 IN (${projects}) OR project_id IN (${projects}))"
   },
   {
    "name": "jobs",
    "label": "Job",
    "query": "SELECT DISTINCT job_id\nFROM events\nWHERE $__timeFilter(timestamp)\n  AND job_id IS NOT NULL\n  AND source = 'client'\n  AND task_id in (${tasks})"
   }
  ]
 },
 "panels": [
  {
   "title": "Mask Creation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT DATE_TRUNC('day', timestamp) as time, user_name, COUNT(*) as \"masks created by\"\r\nFROM cvat.events \r\nWHERE  \r\n    ( scope = 'create:shapes' ) \r\n    AND ( obj_name = 'mask' )\r\n  GROUP BY time, user_name\r\n  ORDER BY time"
    }
   ]
  },
  { "title": "Jobs Completed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Jobs Completed (daily)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT DATE_TRUNC('day', timestamp) as time,\r\n       COUNT(CASE WHEN obj_val = 'completed' THEN 1 END) as \"Jobs completed per day\",\r\n       COUNT(CASE WHEN obj_val = 'rejected' THEN 1 END) as \"Jobs rejected per day\"\r\nFROM events \r\nWHERE $__timeFilter(timestamp)\r\n    AND (scope = 'update:job')\r\n    AND (obj_name = 'status')\r\n    AND (obj_val IN ('completed', 'rejected'))\r\nGROUP BY time\r\nORDER BY time\r\n"
    }
   ]
  },
  {
   "title": "Jobs Completed per User (daily)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT DATE_TRUNC('day', timestamp) as time, user_name as user,\r\n       COUNT(CASE WHEN obj_val IN ('completed', 'rejected') THEN 1 END) as \"Done by\"\r\nFROM events \r\nWHERE $__timeFilter(timestamp)\r\n    AND (scope = 'update:job')\r\n    AND (obj_name = 'status')\r\n    AND (obj_val IN ('completed', 'rejected'))\r\nGROUP BY time, user\r\nORDER BY time, user"
    }
   ]
  },
  {
   "title": "Jobs Completed (hourly)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT DATE_TRUNC('hour', timestamp) as time,\r\n       COUNT(CASE WHEN obj_val = 'completed' THEN 1 END) as \"Jobs completed per hour\",\r\n       COUNT(CASE WHEN obj_val = 'rejected' THEN 1 END) as \"Jobs rejected per hour\"\r\nFROM events \r\nWHERE $__timeFilter(timestamp)\r\n    AND (scope = 'update:job')\r\n    AND (obj_name = 'status')\r\n    AND (obj_val IN ('completed', 'rejected'))\r\nGROUP BY time\r\nORDER BY time\r\n"
    }
   ]
  },
  {
   "title": "Jobs Completed per User (hourly)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT DATE_TRUNC('hour', timestamp) as time, user_name as user,\r\n       COUNT(CASE WHEN obj_val IN ('completed', 'rejected') THEN 1 END) as \"Done by\"\r\nFROM events \r\nWHERE $__timeFilter(timestamp)\r\n    AND (scope = 'update:job')\r\n    AND (obj_name = 'status')\r\n    AND (obj_val IN ('completed', 'rejected'))\r\nGROUP BY time, user\r\nORDER BY time, user"
    }
   ]
  },
  {
   "title": "Average Jobs completed per active hour (daily)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "WITH user_activity AS (\r\n    SELECT DISTINCT DATE_TRUNC('hour', timestamp) AS time,\r\n           toString(user_name) AS user\r\n    FROM events\r\n    WHERE $__timeFilter(timestamp)\r\n    ),\r\nuser_jobs AS (\r\n    SELECT DATE_TRUNC('hour', timestamp) AS time,\r\n           user_name AS user,\r\n           COUNT(CASE WHEN obj_val IN ('completed', 'rejected') THEN 1 END) AS done_by\r\n    FROM events \r\n    WHERE $__timeFilter(timestamp)\r\n        AND (scope = 'update:job')\r\n        AND (obj_name = 'status')\r\n        AND (obj_val IN ('completed', 'rejected'))\r\n        GROUP BY time, user\r\n)\r\nSELECT DATE_TRUNC('day', ua.time) as time,\r\n       COALESCE(SUM(uj.done_by) / COUNT(ua.time), 0) AS \"Average jobs completed per hour\"\r\nFROM user_activity ua\r\nLEFT JOIN user_jobs uj ON ua.time = uj.time AND ua.user = uj.user\r\nGROUP BY time\r\nORDER BY time;\r\n"
    }
   ]
  },
  {
   "title": "Average Jobs per active hour and user (daily)",
   "type": "barchart",
   "description": "For each day, the number of jobs a user completed divided by the number of active hours they had.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "rawSql": "WITH user_activity AS (\r\n    SELECT DISTINCT DATE_TRUNC('hour', timestamp) AS time,\r\n           toString(user_name) AS user\r\n    FROM events\r\n    WHERE $__timeFilter(timestamp)\r\n    ),\r\nuser_jobs AS (\r\n    SELECT DATE_TRUNC('hour', timestamp) AS time,\r\n           user_name AS user,\r\n           COUNT(CASE WHEN obj_val IN ('completed', 'rejected') THEN 1 END) AS done_by\r\n    FROM events \r\n    WHERE $__timeFilter(timestamp)\r\n        AND (scope = 'update:job')\r\n        AND (obj_name = 'status')\r\n        AND (obj_val IN ('completed', 'rejected'))\r\n        GROUP BY time, user\r\n)\r\nSELECT DATE_TRUNC('day', ua.time) as time,\r\n       ua.user,\r\n       COALESCE(uj.done_by / COUNT(ua.time), 0) AS \"Average jobs completed per active hour by\"\r\nFROM user_activity ua\r\nLEFT JOIN user_jobs uj ON ua.time = uj.time AND ua.user = uj.user\r\nGROUP BY time, ua.user, uj.done_by\r\nORDER BY time, ua.user;\r\n"
    }
   ]
  },
  { "title": "Time to Complete Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Avg time [m] from opening to completing a job",
   "type": "barchart",
   "description": "Overall time from job opening to job completion",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT\r\n     DATE_TRUNC('day', e2.timestamp) as time,\r\n    AVG(TIMESTAMPDIFF(MINUTE, e1.timestamp, e2.timestamp)) AS \"Overall average minutes to complete a job\"\r\nFROM events e1\r\nLEFT JOIN events e2 ON e1.job_id = e2.job_id\r\nWHERE\r\n    $__timeFilter(e1.timestamp) AND e1.scope = 'load:job'\r\n    AND (($__timeFilter(e2.timestamp) AND e2.scope = 'update:job' AND (e2.obj_val = 'completed' OR e2.obj_val = 'rejected')))\r\n    AND e1.timestamp < e2.timestamp\r\n    AND e1.user_name = e2.user_name\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Avg time [m] from opening to completing job per user",
   "type": "barchart",
   "description": "Minutes  from job opening to job completion",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "rawSql": "SELECT\r\n     DATE_TRUNC('day', e2.timestamp) as time,\r\n    e2.user_name AS user,\r\n    AVG(TIMESTAMPDIFF(MINUTE, e1.timestamp, e2.timestamp)) AS \"Avg minutes from opening to completing job by\"\r\nFROM events e1\r\nLEFT JOIN events e2 ON e1.job_id = e2.job_id\r\nWHERE\r\n    $__timeFilter(e1.timestamp) AND e1.scope = 'load:job'\r\n    AND (($__timeFilter(e2.timestamp) AND e2.scope = 'update:job' AND (e2.obj_val = 'completed' OR e2.obj_val = 'rejected')))\r\n    AND e1.timestamp < e2.timestamp\r\n    AND e1.user_name = e2.user_name\r\nORDER BY time, user"
    }
   ]
  },
  {
   "title": "Avg time [s] to complete a job per working time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "rawSql": "WITH time_per_job AS (\r\n    SELECT\r\n        user_name as user,\r\n        job_id as job,\r\n        sum(JSONExtractUInt(payload, 'working_time')) / 1000 as time_per_job\r\n    FROM events\r\n    WHERE JSONHas(payload, 'working_time')\r\n      AND $__timeFilter(timestamp)\r\n        AND source = 'client'\r\n    GROUP BY user_name, job_id\r\n),\r\n     completed_jobs AS (\r\n         SELECT DATE_TRUNC('day', timestamp) AS time,\r\n                user_name AS user,\r\n                job_id as job,\r\n                COUNT(CASE WHEN obj_val IN ('completed', 'rejected') THEN 1 END) AS done_by\r\n         FROM events\r\n         WHERE $__timeFilter(timestamp)\r\n           AND (scope = 'update:job')\r\n           AND (obj_name = 'status')\r\n           AND (obj_val IN ('completed', 'rejected'))\r\n                GROUP BY time, user, job_id\r\n     )\r\nSELECT DATE_TRUNC('day', completed.time) as time,\r\n       AVG(job_time.time_per_job) AS \"Average seconds to complete job\"\r\nFROM completed_jobs AS completed\r\n         LEFT JOIN time_per_job AS job_time ON completed.job = job_time.job AND completed.user = job_time.user\r\nGROUP BY time\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Average time [s] to complete job per working time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "rawSql": "WITH time_per_job AS (\r\n    SELECT\r\n        user_name as user,\r\n        job_id as job,\r\n        sum(JSONExtractUInt(payload, 'working_time')) / 1000 as time_per_job\r\n    FROM events\r\n    WHERE JSONHas(payload, 'working_time')\r\n      AND $__timeFilter(timestamp)\r\n      AND user_name IN (${users})\r\n      AND source = 'client'\r\n    GROUP BY user_name, job_id\r\n),\r\ncompleted_jobs AS (\r\n    SELECT DATE_TRUNC('day', timestamp) AS time,\r\n           user_name AS user,\r\n           job_id as job,\r\n           COUNT(CASE WHEN obj_val IN ('completed', 'rejected') THEN 1 END) AS done_by\r\n    FROM events\r\n    WHERE $__timeFilter(timestamp)\r\n        AND (scope = 'update:job')\r\n        AND (obj_name = 'status')\r\n        AND (obj_val IN ('completed', 'rejected'))\r\nGROUP BY time, user, job_id\r\n)\r\nSELECT DATE_TRUNC('day', completed.time) as time,\r\n       completed.user as user,\r\n       AVG(job_time.time_per_job) AS \"Average seconds to complete job by\"\r\nFROM completed_jobs AS completed\r\n         LEFT JOIN time_per_job AS job_time ON completed.job = job_time.job AND completed.user = job_time.user\r\nGROUP BY time, completed.user\r\nORDER BY time, completed.user;\r\n"
    }
   ]
  },
  { "title": "Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Overall Activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as time,  count(*) \"Number_of_activities\" FROM events WHERE $__timeFilter(timestamp) GROUP BY time ORDER BY time ASC LIMIT 100"
    }
   ]
  },
  {
   "title": "User Activity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "rawSql": "SELECT DATE_TRUNC('hour', timestamp) as time, toString(user_name), count() as User\r\nFROM events\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY time, user_name\r\nORDER BY time ASC, user_name ASC"
    }
   ]
  },
  {
   "title": "Working time",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  user_name as User,\r\n  project_id as Project,\r\n  task_id as Task,\r\n  job_id as Job, sum(JSONExtractUInt(payload, 'working_time')) / 1000 / 3600 as \"Working time(h)\",\r\n  count() as Activity\r\nFROM events\r\nWHERE JSONHas(payload, 'working_time')\r\n  AND $__timeFilter(timestamp)\r\n  AND user_name IN (${users})\r\n  AND (-1 IN (${projects}) OR project_id IN (${projects}))\r\n  AND task_id IN (${tasks})\r\n  AND job_id IN (${jobs})\r\n  AND source = 'client'\r\nGROUP BY user_name, project_id, task_id, job_id"
    }
   ]
  }
 ]
}